from django.contrib import admin
from .views import *

admin.site.register(MainInfo)
admin.site.register(Carousel)
admin.site.register(Category)
admin.site.register(SubCategory)
admin.site.register(Gallery)
admin.site.register(Items)
admin.site.register(ItemsName)
admin.site.register(Products)
admin.site.register(ItemsDetails)
admin.site.register(ItemsImages)
admin.site.register(ReviewMessage)
admin.site.register(UserSave)
admin.site.register(UserFor)
admin.site.register(Total_payment)
admin.site.register(UserInfo)
admin.site.register(model404)
admin.site.register(Payments_History)