# Generated by Django 5.1.6 on 2025-04-14 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsersRegisteringCountinMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Month', models.CharField(default='April', max_length=20, verbose_name='Month')),
                ('Year', models.CharField(default='2025', max_length=20, verbose_name='Year')),
                ('Count', models.IntegerField(default=0, verbose_name='Registering count')),
            ],
        ),
    ]
