# Generated by Django 5.1.6 on 2025-04-14 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Value', models.FloatField(default=0, verbose_name='Value')),
                ('Users', models.IntegerField(default=0, verbose_name='Users')),
                ('Orders', models.IntegerField(default=0, verbose_name='Orders')),
            ],
        ),
    ]
