# Generated by Django 5.1.6 on 2025-03-07 17:56

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Site name')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Phone')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('facebook', models.URLField(verbose_name='Faceboook')),
                ('twitter', models.URLField(verbose_name='Twitter')),
                ('linkedin', models.URLField(verbose_name='LinkedIn')),
                ('dribbble', models.URLField(verbose_name='Dribbble')),
                ('googleplus', models.URLField(verbose_name='Google Plus')),
            ],
        ),
    ]
