# Generated by Django 5.1.6 on 2025-03-07 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maininfo',
            name='img',
            field=models.ImageField(null=True, upload_to='', verbose_name='Logoname'),
        ),
    ]
