# Generated by Django 5.1.6 on 2025-03-07 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_maininfo_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='maininfo',
            name='info',
            field=models.TextField(null=True, verbose_name='Text'),
        ),
    ]
