# Generated by Django 5.1.6 on 2025-03-07 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_maininfo_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='maininfo',
            name='owner',
            field=models.CharField(max_length=20, null=True, verbose_name='Owner'),
        ),
    ]
