# Generated by Django 5.1.6 on 2025-03-09 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_maininfo_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text1', models.TextField(verbose_name='text1')),
                ('text2', models.TextField(verbose_name='text2')),
                ('img', models.ImageField(upload_to='Images', verbose_name='Girls image')),
                ('disc_img', models.ImageField(upload_to='Images', verbose_name='Discount image')),
            ],
        ),
    ]
