# Generated by Django 5.1.6 on 2025-03-09 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_category_subcategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name': 'Subcategory', 'verbose_name_plural': 'Subcategories'},
        ),
    ]
