# Generated by Django 5.1.6 on 2025-03-09 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_category_options_alter_subcategory_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carousel',
            options={'verbose_name': 'Main Info', 'verbose_name_plural': 'Main Info'},
        ),
    ]
