# Generated by Django 5.1.6 on 2025-03-09 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_carousel_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory',
            old_name='name',
            new_name='subname',
        ),
    ]
