# Generated by Django 5.1.6 on 2025-03-09 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_category_sub_bool'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='sub_bool',
        ),
    ]
