# Generated by Django 5.1.6 on 2025-03-10 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_category_sub_bool'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Items name')),
                ('price', models.IntegerField(verbose_name='Price')),
                ('img', models.ImageField(upload_to='Images', verbose_name='Image')),
                ('info', models.TextField(verbose_name='Info')),
                ('brand', models.CharField(max_length=30, verbose_name='Brand')),
                ('reccomend_bool', models.BooleanField(default=False, verbose_name='Reccom. or not')),
                ('discount', models.IntegerField(verbose_name='Discount')),
                ('key1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_rn', to='main.category')),
                ('key2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcat_rn', to='main.subcategory')),
            ],
        ),
    ]
