# Generated by Django 5.1.6 on 2025-03-10 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='date',
            field=models.CharField(max_length=30, null=True, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='desc',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
    ]
