# Generated by Django 5.1.6 on 2025-03-10 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_gallery_date_gallery_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='disc_icon',
            field=models.ImageField(null=True, upload_to='', verbose_name='Discount Icon'),
        ),
    ]
