# Generated by Django 5.1.6 on 2025-03-11 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_items_disc_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemsName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Items name(category)')),
            ],
        ),
        migrations.RemoveField(
            model_name='items',
            name='name',
        ),
        migrations.AddField(
            model_name='items',
            name='key3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itemsname_rn', to='main.itemsname'),
        ),
    ]
