# Generated by Django 5.1.6 on 2025-03-11 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_itemsname_remove_items_name_items_key3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='key2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcat_rn', to='main.subcategory'),
        ),
    ]
