# Generated by Django 5.1.6 on 2025-03-11 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_items_key2'),
    ]

    operations = [
        migrations.AddField(
            model_name='maininfo',
            name='add',
            field=models.ImageField(blank=True, null=True, upload_to='Images', verbose_name='Addvertisement'),
        ),
        migrations.AlterField(
            model_name='items',
            name='key2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcat_rn', to='main.subcategory'),
        ),
    ]
