# Generated by Django 5.1.6 on 2025-03-12 05:00

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_maininfo_add_alter_items_key2'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('surname', models.CharField(max_length=30, verbose_name='Surname')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Phone')),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
                ('birthday', models.DateField(verbose_name='Birthday')),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customuser_rn', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
