# Generated by Django 5.1.6 on 2025-03-12 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customuser',
        ),
    ]
