# Generated by Django 5.1.6 on 2025-03-17 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemsDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moreinfo', models.TextField(verbose_name='Description')),
                ('availability', models.BooleanField(verbose_name='Availability')),
                ('condition', models.BooleanField(verbose_name='Condition')),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_details_rn', to='main.items')),
            ],
            options={
                'verbose_name': 'ItemDetails',
                'verbose_name_plural': 'ItemsDetails',
            },
        ),
        migrations.CreateModel(
            name='ItemsImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='Images', verbose_name='Carousel Images')),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_images_rn', to='main.items')),
            ],
        ),
    ]
