# Generated by Django 5.1.6 on 2025-03-17 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_reviewmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewmessage',
            name='key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews_rn', to='main.items'),
        ),
    ]
