# Generated by Django 5.1.6 on 2025-03-18 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_reviewmessage_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='condition_img',
            field=models.ImageField(null=True, upload_to='Images', verbose_name='New or Old Item'),
        ),
    ]
