# Generated by Django 5.1.6 on 2025-03-19 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_remove_items_condition_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemsdetails',
            name='review_date',
            field=models.DateField(auto_created=True, null=True, verbose_name='Reviews date'),
        ),
        migrations.AddField(
            model_name='itemsdetails',
            name='review_time',
            field=models.TimeField(auto_created=True, null=True, verbose_name='Reviews time'),
        ),
    ]
