# Generated by Django 5.1.6 on 2025-03-19 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_itemsdetails_review_date_itemsdetails_review_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemsdetails',
            name='review_date',
        ),
        migrations.RemoveField(
            model_name='itemsdetails',
            name='review_time',
        ),
        migrations.AddField(
            model_name='reviewmessage',
            name='review_date',
            field=models.DateField(auto_created=True, null=True, verbose_name='Reviews date'),
        ),
        migrations.AddField(
            model_name='reviewmessage',
            name='review_time',
            field=models.TimeField(auto_created=True, null=True, verbose_name='Reviews time'),
        ),
    ]
