# Generated by Django 5.1.6 on 2025-03-19 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_remove_itemsdetails_review_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewmessage',
            name='review_date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Reviews date'),
        ),
        migrations.AlterField(
            model_name='reviewmessage',
            name='review_time',
            field=models.TimeField(auto_now_add=True, null=True, verbose_name='Reviews time'),
        ),
    ]
