# Generated by Django 5.1.6 on 2025-03-24 14:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_usersave'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ver_code', models.IntegerField(blank=True, null=True, verbose_name='verification code')),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_rn', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
