# Generated by Django 5.1.6 on 2025-03-26 09:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_userfor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersave',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
