# Generated by Django 5.1.6 on 2025-03-26 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_alter_cart_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
