# Generated by Django 5.1.6 on 2025-03-26 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
