# Generated by Django 5.1.6 on 2025-03-26 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='quantity',
            field=models.IntegerField(null=True, verbose_name='Items number in cart'),
        ),
    ]
