# Generated by Django 5.1.6 on 2025-03-26 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_alter_items_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='Items number in cart'),
        ),
    ]
