# Generated by Django 5.1.6 on 2025-03-26 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_alter_items_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='quantity',
        ),
        migrations.AddField(
            model_name='usersave',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='Items number in cart'),
        ),
    ]
