# Generated by Django 5.1.6 on 2025-03-27 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_usersave_line_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='Total_payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Eco_Tax', models.IntegerField(verbose_name='Eco Tax Price')),
                ('Shipping_Cost', models.IntegerField(verbose_name='Shipping_Cost')),
            ],
        ),
    ]
