# Generated by Django 5.1.6 on 2025-03-27 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_total_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='maininfo',
            name='map_img',
            field=models.ImageField(null=True, upload_to='Images', verbose_name='Map'),
        ),
    ]
