# Generated by Django 5.1.6 on 2025-03-27 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_maininfo_map_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='maininfo',
            name='adress',
            field=models.CharField(max_length=255, null=True, verbose_name='Adress'),
        ),
    ]
