# Generated by Django 5.1.6 on 2025-03-29 18:58

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_maininfo_adress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment', models.CharField(max_length=255, verbose_name='Payment')),
                ('Payment_date', models.DateField(auto_now_add=True, null=True, verbose_name='Payments date')),
                ('Payments_time', models.TimeField(auto_now_add=True, null=True, verbose_name='Payments time')),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_rn', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name="User's name")),
                ('surname', models.CharField(max_length=255, verbose_name="User's surname")),
                ('img', models.ImageField(upload_to='', verbose_name="User's image")),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name="User's phone number")),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userinfo_rn', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
