# Generated by Django 5.1.6 on 2025-03-29 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0051_remove_userinfo_img_userinfo_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='user_image',
        ),
    ]
