# Generated by Django 5.1.6 on 2025-03-29 22:34

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0053_alter_userinfo_adress_alter_userinfo_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='adress',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Delivery adress'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name="User's name"),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name="User's phone number"),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='surname',
            field=models.CharField(blank=True, max_length=255, verbose_name="User's surname"),
        ),
    ]
