# Generated by Django 5.1.6 on 2025-03-30 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0054_alter_userinfo_adress_alter_userinfo_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersave',
            name='line_total',
        ),
    ]
