# Generated by Django 5.1.6 on 2025-03-30 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0055_remove_usersave_line_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='model404',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='Images', verbose_name='error Image')),
            ],
        ),
    ]
